config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  
  concern :votable do
    member do
      post :down
      post :up
      post :cancel_vote
    end
  end

  resources :questions, concerns: :votable, shallow: true do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, shallow: true, concerns: :votable do
      member do
        post :select_best
      end
  	end
  end
  resources :rewards, only: :index
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: %i[create destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy], shallow: true do
        resources :answers, only: %i[index show create update destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'

  get 'search', to: 'search#index'
end

app/models/question.rb
class Question < ApplicationRecord
  include Authorable
  include Votable
  include Commentable
  
  # https://guides.rubyonrails.org/association_basics.html
  # https://apidock.com/rails/ActiveRecord/Associations/ClassMethods/has_many
  has_many :answers, -> { order('best DESC, created_at') }, dependent: :destroy
  has_many_attached :files
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  has_one :reward, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :calculate_reputation
  after_create :create_subscription

  scope :created_prev_day, -> { where(created_at: Date.today.prev_day.all_day) }
    
  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
  
  def create_subscription
    user.subscriptions.find_or_create_by(question_id: id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: %i[show update destroy]

  authorize_resource

  def index
    @questions = Question.order(:created_at)
    render json: @questions
  end

  def show
    render json: @question, serializer: QuestionShowSerializer
  end

  def create
    @question = current_resource_owner.questions.new(question_params)
    if @question.save
      render json: @question, status: :created
    else
      render json: {errors: @question.errors}, status: :unprocessable_entity
    end 
  end

  def update
    if @question.update(question_params)
      render json: @question, status: :ok
    else
      render json: {errors: @question.errors}, status: :unprocessable_entity
    end 
  end

  def destroy
    @question.destroy
    head :no_content
  end

  private

  def question_params
    params.require(:question).permit(
      :title, 
      :body,
      links_attributes: %i[name url]
    )
  end

  def set_question
    @question = Question.with_attached_files.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  layout :false, only: %i[update]
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  before_action :check_question_author, only: :update
  after_action :publish_question, only: :create

  authorize_resource

  include Voted

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.build
    @comment = @question.comments.build
  end

  def new
    @question = Question.new
    @question.build_reward
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    if current_user.author?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Question was successfully deleted.'
    else
      return redirect_to questions_path, 
      notice: "Deletion is not available! \
               You are not the author of the question."
    end
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                      links_attributes: %i[name url], 
                                      reward_attributes: %i[title file])
  end

  def check_question_author
    unless current_user.author?(@question)
      head(:forbidden)
    end
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      question: @question
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_form_options(question)
    if question.new_record?
      {model: question, local: true}
    else
      {model: question, class: 'hidden', id: "edit-question-#{question.id}"}
    end
  end
end

app/views/questions/_form.slim
= form_with question_form_options(question) do |f|
  #question-errors
    = render 'shared/errors', resource: question
  p
    = f.label :title, 'Topic of the question'
    = f.text_field :title
  p
    = f.label :body, 'Your question'
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  = f.fields_for :reward do |reward|
    p
      = reward.label :title, 'Reward title'
      = reward.text_field :title
    p
      = reward.label :file, 'Reward file'
      = reward.file_field :file

  .question-links
    = f.fields_for :links do |link|
      = render 'links/link_fields', f: link
    p.links
      = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

  p= f.submit question.new_record? ? 'Ask' : 'Save'

app/views/questions/_question.slim
.question id="question-#{@question.id}" data-question-id=@question.id
  h1 = @question.title
  p = @question.body

  div id="comments-question-#{@question.id}"
    = render 'comments/index', resource: @question

    - if can?(:create, @comment)
      p 
        = link_to 'Add comment', '#', class: 'add-comment-link btn btn-link', data: {url: comments_path(id: @question, commentable: 'questions'), resourсe_id: @question.id, resourсe_type: 'question'}

        = render 'comments/form', comment: @comment

  - is_author = current_user&.author?(@question)

  div id="vote-question-#{@question.id}"
    p
      span Rating: 
      span.rating = @question.rating
            
    - if current_user
      - unless is_author
        =render 'votes/block', resource: @question

    - if can?(:create, Subscription)
      = link_to('Subscribe', question_subscriptions_path(@question), method: :post, remote: true,
              class: "subscribe-question-link #{current_user.subscribed?(@question) ? 'hidden' : ''}")
    - if can?(:destroy, Subscription)
      = link_to('Unsubscribe', subscription_path(@question), method: :delete, remote: true,
              class: "unsubscribe-question-link #{current_user.subscribed?(@question) ? '' : 'hidden'}")
 
  - if @question.files.attached?
    - @question.files.each do |file|
      p id="attachment-#{file.id}"
        span = link_to file.filename.to_s, url_for(file)
        - if is_author
          span = link_to 'Delete file', attachment_path(file), method: :delete, remote: true, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'

  - if @question.reward
    = render @question.reward

  -if @question&.links.present?
    = render 'links/index', resource: @question

  - if is_author
    p
      - if can?(:update, @question)  
        span = link_to 'Edit question', '#', class: 'edit-question-link btn btn-info' , data: { question_id: @question.id }
      - if can?(:destroy, @question)  
        span = link_to 'Delete question', question_path(@question), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' 

    div id="question-#{@question.id}-errors"
      = render 'shared/short_errors', resource: @question

    - if can?(:create, @question)  
      = render 'questions/form', question: @question

app/views/questions/index.slim
- cache collection_cache_key_for :question do
  h1 Questions list
  ul.questions-list
    - @questions.each do |question|
      li = link_to question.title, question

  - if can?(:create, Question)
    p = link_to 'Ask question', new_question_path

app/views/questions/new.slim
= render 'shared/errors', resource: @question

= render 'questions/form', question: @question

p = link_to 'Back', questions_path

app/views/questions/show.slim
#vouting.comments-area  data-resourсe-id=@question.id data-resourсe-type="question" 
  - cache @question do
    = render @question

    h2 Answers
    .answers id="answers-#{@question.id}"
      = render @question.answers

  - if user_signed_in?
    = render 'answers/form', answer: @answer

p = link_to 'Back', questions_path

app/views/questions/update.js.erb
<% if @question.links.any?(&:gist?) %>
  window.location.reload(false); // fix partial view of question script
<% else %>
  <% if @question.errors.blank? %>
    $("#question-<%= @question.id %>").replaceWith('<%= j render @question %>');
  <% else %>
    $('#question-<%= @question.id %>-errors').html('<%= j render 'shared/errors', resource: @question %>');
  <% end %>
<% end %>