config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  
  concern :votable do
    member do
      post :down
      post :up
      post :cancel_vote
    end
  end

  resources :questions, concerns: :votable, shallow: true do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, shallow: true, concerns: :votable do
      member do
        post :select_best
      end
  	end
  end
  resources :rewards, only: :index
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: %i[create destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy], shallow: true do
        resources :answers, only: %i[index show create update destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'

  get 'search', to: 'search#index'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    authorize! :index, :search

    @results = Search.new(params[:context], params[:q]).call
  end
end

app/views/search/_answer.slim
h3 Answer
p = link_to object.question.title.truncate(80), question_path(object.question)
p = object.body.truncate(200)

app/views/search/_comment.slim
h3 Comment
p = link_to object.commentable.body.truncate(80), object.commentable.is_a?(Question) ? question_path(object.commentable) : question_path(object.commentable.question)
p = object.body.truncate(200)

app/views/search/_form.slim
= form_tag search_path, method: :get do
  = text_field_tag :q, params[:q], type: 'search', placeholder: 'Search'
  = select_tag :context, options_for_select(%w[All Question Answer Comment User], params[:context])
  = submit_tag 'Search', class: 'btn btn-light'

app/views/search/_question.slim
h3 Question
p = link_to object.title.truncate(80), question_path(object)
p = object.body.truncate(200)

app/views/search/_user.slim
h3 User
p = object.email

app/views/search/index.slim
h2 Search results:
- if @results.empty?
  p= "Nothing has been found"
- else
  - @results.each do |object|
    = render "search/#{object.class.name.underscore}", object: object