config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  
  concern :votable do
    member do
      post :down
      post :up
      post :cancel_vote
    end
  end

  resources :questions, concerns: :votable, shallow: true do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, shallow: true, concerns: :votable do
      member do
        post :select_best
      end
  	end
  end
  resources :rewards, only: :index
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :comments, only: %i[create destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy], shallow: true do
        resources :answers, only: %i[index show create update destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'

  get 'search', to: 'search#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Authorable
  include Votable
  include Commentable
  
  belongs_to :question, touch: true

  has_many_attached :files
  has_many :links, dependent: :destroy, as: :linkable
  
  validates :body, presence: true 

  accepts_nested_attributes_for :links, reject_if: :all_blank

  after_create :send_notification

  def select_best!
    Answer.transaction do
      question.answers.update_all(best:false)
      question.reward&.update!(user_id: user_id)
      update!(best: true)
    end
  end
  
  private

  def send_notification
    AnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  layout :false, only: %i[create update destroy select_best]
  before_action :authenticate_user!, except: :show
  before_action :find_question, only: %i[index create]
  before_action :load_answer, only: %i[show edit update destroy select_best]
  before_action :check_answer_author, only: %i[update destroy]
  before_action :check_question_author, only: :select_best
  after_action :publish_answer, only: :create

  authorize_resource

  include Voted

  def index
    @answers = @question.answers
  end

  def show
    @comment = @answer.comments.build
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.create(answer_params.merge(user: current_user))
  end


  def update
    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy
  end

  def select_best
    @answer.select_best!
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [],
                                   links_attributes: [:name, :url])
  end

  def check_question_author
    unless current_user.author?(@answer.question)
      head(:forbidden)
    end
  end

  def check_answer_author
    unless current_user.author?(@answer)
      head(:forbidden)
    end
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "questions_#{@answer.question_id}_answers",
      @answer.attributes.merge(rating: @answer.rating)
    )
  end

end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: %i[index create]
  before_action :set_answer, only: %i[show update destroy]

  authorize_resource

  def index
    render json: @question.answers
  end

  def show
    render json: @answer, serializer: AnswerShowSerializer
  end

  def create
    @answer = @question.answers.new(
      answer_params.merge(user_id: current_resource_owner.id))
    if @answer.save
      render json: @answer, status: :created
    else
      render json: {errors: @answer.errors}, status: :unprocessable_entity
    end 
  end

  def update
    if @answer.update(answer_params)
      render json: @answer, status: :ok
    else
      render json: {errors: @answer.errors}, status: :unprocessable_entity
    end 
  end

  def destroy
    @answer.destroy
    head :no_content
  end


  private

  def answer_params
    params.require(:answer).permit(
      :body,
      links_attributes: %i[name url]
    )
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def answer_form_options(answer)
    if answer.new_record?
      {model: [answer.question, answer]}
    else
      {model: answer, class: 'hidden', id: "edit-answer-#{answer.id}"}
    end
  end

  def answer_errors_div_id(answer)
    answer.new_record? ? 'new-answer-errors' : "answer-#{answer.id}-errors"
  end
end

app/views/answers/_answer.slim
- if answer.persisted?
  - cache answer do
    blockquote id="answer-#{answer.id}" class='answer border border-dark'  data-answer-id=@answer.id
      p = answer.body

      div id="comments-answer-#{answer.id}"
        = render 'comments/index', resource: answer
          
        - if can?(:create, @comment)
          p 
            = link_to 'Add comment', '#', class: 'add-comment-link btn btn-link', data: {url: comments_path(id: answer, commentable: 'answers'), resourсe_id: answer.id, resourсe_type: 'answer'}

            = render 'comments/form', comment: @comment

      - is_author = current_user&.author?(answer)

      div id="vote-answer-#{answer.id}"     
        p
          span Rating: 
          span.rating= answer.rating
          
          - if current_user
            - unless is_author
              =render 'votes/block', resource: answer

      - if answer.files.attached?
        - answer.files.each do |file|
          p id="attachment-#{file.id}"
            span = link_to file.filename.to_s, url_for(file)
            - if is_author
              span = link_to 'Delete file', attachment_path(file), method: :delete, remote: true, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'

      -if answer&.links.present?
        = render 'links/index', resource: answer

      p
        - if can?(:update, answer)
          span = link_to 'Edit answer', '#', class: 'edit-answer-link btn btn-info', data: { answer_id: answer.id }
        - if can?(:destroy, answer)
          span = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' 

      - if can?(:select_best, answer)
        - if answer.best?
          p class='best-answer-title' This is the best answer!
        - else
          p = link_to 'Select best!', select_best_answer_path(answer), class: 'best-answer-link btn btn-success', method: :post, remote: true

      - if can?(:create, Answer)
        = render 'answers/form', answer: answer
        

app/views/answers/_form.slim
= form_with answer_form_options(answer) do |f|
  div id=answer_errors_div_id(answer)
    = render 'shared/short_errors', resource: answer
  .new-answer
    p
      = f.label :body, 'Your answer'
      = f.text_area :body
    p
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true

  .answer-links
    = f.fields_for :links do |link|
      = render 'links/link_fields', f: link
    p.links
      = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

  p= f.submit answer.new_record? ? 'Reply' : 'Save'

app/views/answers/create.js.erb
<% if @answer.links.any?(&:gist?) %>
  window.location.reload(false); // fix partial view of answer script
<% else %>
  $('#new-answer-errors').html('<%= j render 'shared/errors', resource: @answer %>');

  <% if @answer.persisted? %>
    $('.answers').append('<%= j render @answer  %>');
    $('.new-answer #answer_body').val('');
  <% end %>
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').detach();

app/views/answers/select_best.js.erb
$('.answers').html('<%= j render @answer.question.answers %>');

app/views/answers/update.js.erb
<% if @answer.links.any?(&:gist?) %>
  window.location.reload(false);  // fix partial view of question script
<% else %>
  <% if @answer.errors.blank? %>
    $('#answer-<%= @answer.id %>').replaceWith('<%= j render @answer %>');
  <% else %>
    $('#answer-<%= @answer.id %>-errors').html('<%= j render 'shared/short_errors', resource: @answer %>');
  <% end %>
<% end %>